language: python

python:
  - "3.6"

sudo: false
cache: pip

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
    - VERSION="12.0" TESTS="0" LINT_CHECK="0" UNIT_TEST="0"
    - SERVER_OPTIONS="--log-handler=odoo.addons.pos_longpolling:DEBUG"
    - PYLINT_ODOO_JSLINTRC="/home/travis/maintainer-quality-tools/travis/cfg/.jslintrc"

  matrix:
    - LINT_CHECK="1"
    - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"

install:
  - pip install anybox.testing.openerp
  - pip install -r requirements.txt
  - git clone https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success