from . import res_zona
from . import zona2
from . import partner
#from . import stock_picking
from . import route_orders
from . import lx_orders
from . import motivo
from . import partner
from . import hr_employee
from . import pos_session
from . import pricelist
from . import sale_cupon_program
from . import pos_order
from . import pos_quotation
from . import quotation_pos_report